"""empty message

Revision ID: 80f0a29ae6f4
Revises: 3b86f62212d3
Create Date: 2023-10-17 22:01:00.467188

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '80f0a29ae6f4'
down_revision = '3b86f62212d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wins', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('losses', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('draws', sa.Integer(), nullable=True))
        batch_op.drop_column('win_lose_draw')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('win_lose_draw', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_column('draws')
        batch_op.drop_column('losses')
        batch_op.drop_column('wins')

    # ### end Alembic commands ###
